// File generated by FlutterFire CLI (adapted manually).
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAplcaqyJgip7hgVrHFJ489BYCR7DppraU',
    appId: '1:1055928331681:web:b1485354c5275b460eafe0',
    messagingSenderId: '1055928331681',
    projectId: 'ecommerceapp-23071',
    authDomain: 'ecommerceapp-23071.firebaseapp.com',
    storageBucket: 'ecommerceapp-23071.firebasestorage.app',
    measurementId: 'G-78Q9EH08S6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY_HERE',
    appId: 'YOUR_ANDROID_APP_ID_HERE',
    messagingSenderId: 'YOUR_ANDROID_MESSAGING_SENDER_ID_HERE',
    projectId: 'ecommerceapp-23071',
    storageBucket: 'ecommerceapp-23071.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAplcaqyJgip7hgVrHFJ489BYCR7DppraU',
    appId: '1:1055928331681:web:b1485354c5275b460eafe0',
    messagingSenderId: '1055928331681',
    projectId: 'ecommerceapp-23071',
    authDomain: 'ecommerceapp-23071.firebaseapp.com',
    storageBucket: 'ecommerceapp-23071.firebasestorage.app',
  );
}
